//solicitamos todas las notas a nuestro servidor 
GET http://localhost:3001/api/notes

###

//solicitamos notas individuales segun id 
GET http://localhost:3001/api/notes/61f93c93ff3d3d5ae0500afb

###

//borramos notas segun id 
DELETE http://localhost:3001/api/notes/61f93c93ff3d3d5ae0500afb

###

// actualizamos una nota segun id 
PUT http://localhost:3001/api/notes/61f99a63b1d9e42d55cdc230
Content-Type: application/json

{
  "content": "fourth note with token update",
  "important": false
}

###

//creamos un nuevo registro en nuestra base de datos 
POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZmUzYzAyNmNkYzk5YTY1YWQ5MmMwMyIsImVtYWlsIjoiV2lsbHlAZ21haWwuY29tIiwidXNlcm5hbWUiOiJXaWxseSIsImlhdCI6MTY0NDA1Mjc0MywiZXhwIjoxNjQ0MTM5MTQzfQ.N-fwMrJLJssDS9vZKaQfwwvih4-12Z2TlFbEq1oHPeo

{
  "title":"usuario willy",
  "content": "veamos si funciona", 
  "important": true
}